# Generated by Django 3.2.25 on 2024-11-01 23:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('images', '0001_initial'),
        ('reports', '0001_initial'),
        ('species', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='report',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.report'),
        ),
        migrations.AddField(
            model_name='image',
            name='species',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='species.species'),
        ),
    ]
